
datase<-read.csv('Kidney_disease.csv')
datase$sg=ifelse(is.na(datase$sg),ave(datase$sg,FUN=function(x) mean(x,na.rm=TRUE)),datase$sg)
datase$al=ifelse(is.na(datase$al),ave(datase$al,FUN=function(x) mean(x,na.rm=TRUE)),datase$al)
datase$su=ifelse(is.na(datase$su),ave(datase$su,FUN=function(x) mean(x,na.rm=TRUE)),datase$su)
datase$age=ifelse(is.na(datase$age),ave(datase$age,FUN=function(x) mean(x,na.rm=TRUE)),datase$age)
datase$bp=ifelse(is.na(datase$bp),ave(datase$bp,FUN=function(x) mean(x,na.rm=TRUE)),datase$bp)
datase$bgr=ifelse(is.na(datase$bgr),ave(datase$bgr,FUN=function(x) mean(x,na.rm=TRUE)),datase$bgr)
datase$bu=ifelse(is.na(datase$bu),ave(datase$bu,FUN=function(x) mean(x,na.rm=TRUE)),datase$bu)
datase$sc=ifelse(is.na(datase$sc),ave(datase$sc,FUN=function(x) mean(x,na.rm=TRUE)),datase$sc)
datase$sod=ifelse(is.na(datase$sod),ave(datase$sod,FUN=function(x) mean(x,na.rm=TRUE)),datase$sod)
datase$pot=ifelse(is.na(datase$pot),ave(datase$pot,FUN=function(x) mean(x,na.rm=TRUE)),datase$pot)
datase$hemo=ifelse(is.na(datase$hemo),ave(datase$hemo,FUN=function(x) mean(x,na.rm=TRUE)),datase$hemo)
datase$pcv=ifelse(is.na(datase$pcv),ave(datase$pcv,FUN=function(x) mean(x,na.rm=TRUE)),datase$pcv)
datase$wc=ifelse(is.na(datase$wc),ave(datase$wc,FUN=function(x) mean(x,na.rm=TRUE)),datase$wc)
datase$rc=ifelse(is.na(datase$rc),ave(datase$rc,FUN=function(x) mean(x,na.rm=TRUE)),datase$rc)
library(caTools)
set.seed(123)
split=sample.split(datase$classification,SplitRatio = 0.8)
trai1_set=subset(datase,split==TRUE)
tes1_set=subset(datase,split==FALSE)
index=nrow(datase)
index=index+5
data = data.frame(age=73,bp=80.00000,sg=1.02000,al=2.00000,su=0.00000,rbc='abnormal',pc='abnormal',pcc='notpresent',ba='notpresent',bgr=253.00000,bu=142.00000,sc=4.60000,sod=138.00000,pot=5.80000,hemo=10.50000,pcv=33.00000,wc=7200.00000,rc=4.30000,htn='yes',dm='yes',cad='yes',appet='poor',pe='no',ane='no',classification='notckd')
tes1_set=rbind(tes1_set,data)
trai1_set$rbc = factor(trai1_set$rbc, levels = c('normal','abnormal'), labels = c(0, 1))
trai1_set$pc = factor(trai1_set$pc, levels = c('normal','abnormal'), labels = c(0, 1))
trai1_set$pcc = factor(trai1_set$pcc, levels = c('present','notpresent'), labels = c(0, 1))
trai1_set$ba = factor(trai1_set$ba, levels = c('present','notpresent'), labels = c(0, 1))
trai1_set$htn = factor(trai1_set$htn, levels = c('no','yes'), labels = c(0, 1))
trai1_set$dm = factor(trai1_set$dm, levels = c('no','yes'), labels = c(0, 1))
trai1_set$cad = factor(trai1_set$cad, levels = c('no','yes'), labels = c(0, 1))
trai1_set$appet = factor(trai1_set$appet, levels = c('good','poor'), labels = c(0, 1))
trai1_set$pe = factor(trai1_set$pe, levels = c('no','yes'), labels = c(0, 1))
trai1_set$ane = factor(trai1_set$ane, levels = c('no','yes'), labels = c(0, 1))
trai1_set$classification = factor(trai1_set$classification, levels = c('ckd','notckd'), labels = c(0, 1))
tes1_set$rbc = factor(tes1_set$rbc, levels = c('normal','abnormal'), labels = c(0, 1))
tes1_set$pc = factor(tes1_set$pc, levels = c('normal','abnormal'), labels = c(0, 1))
tes1_set$pcc = factor(tes1_set$pcc, levels = c('present','notpresent'), labels = c(0, 1))
tes1_set$ba = factor(tes1_set$ba, levels = c('present','notpresent'), labels = c(0, 1))
tes1_set$htn = factor(tes1_set$htn, levels = c('no','yes'), labels = c(0, 1))
tes1_set$dm = factor(tes1_set$dm, levels = c('no','yes'), labels = c(0, 1))
tes1_set$cad = factor(tes1_set$cad, levels = c('no','yes'), labels = c(0, 1))
tes1_set$appet = factor(tes1_set$appet, levels = c('good','poor'), labels = c(0, 1))
tes1_set$pe = factor(tes1_set$pe, levels = c('no','yes'), labels = c(0, 1))
tes1_set$ane = factor(tes1_set$ane, levels = c('no','yes'), labels = c(0, 1))
tes1_set$classification = factor(tes1_set$classification, levels = c('ckd','notckd'), labels = c(0, 1))
ind<-sapply(trai1_set,is.numeric)
trai1_set[ind] <-lapply(trai1_set[ind], scale)
ind<-sapply(tes1_set,is.numeric)
tes1_set[ind] <-lapply(tes1_set[ind], scale)
library(sandwich)
library(stats4)
library(strucchange)
library(grid)
library(mvtnorm)
library(modeltools)
library(randomForest)
library(rpart)
classifier = rpart(formula = classification~., data = trai1_set)
 y_pred = predict(classifier, newdata = tes1_set[-25])
 print(y_pred[nrow(y_pred)])